---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-domain-com
  namespace: cert-manager
spec:
  # secretName: local-domain-com-staging-tls
  secretName: local-domain-com-prod-tls
  issuerRef:
    name: letsencrypt-production
    # name: letsencrypt-staging #for staging
    kind: ClusterIssuer
  commonName: "*.local.domain.com"
  dnsNames:
  - "local.domain.com"
  - "*.local.domain.com"