all:
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master_main:
              ansible_host: 192.168.1.108
        workers:
          hosts:
            192.168.1.110: {}
            192.168.1.111: {}
    ungrouped: {}
