all:
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master_main:
              ansible_host: 192.168.1.119
        workers:
          hosts:
            192.168.1.117: {}
            192.168.1.118: {}
    ungrouped: {}
