replicas: 1

# image:
#   repository: ghcr.io/goauthentik/server
#   tag: 2023.2.2
#   # -- optional container image digest
#   digest: ""
#   pullPolicy: IfNotPresent



authentik:
  secret_key: ""
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
      enabled: true
  redis:
    host: 192.168.1.27
  postgresql:
    host: 192.168.1.26
    password: "password"
  email:
    # -- SMTP Server emails are sent from, fully optional
    host: ""
    port: 587
    # -- SMTP credentials, when left empty, not authentication will be done
    username: ""
    # -- SMTP credentials, when left empty, not authentication will be done
    password: ""
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_tls: true
    # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
    timeout: 30
    # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
    from: ""

ingress:
  enabled: true
  hosts:
      - host: authentik.domain.com
        paths:
            - path: "/"
              pathType: Prefix

postgresql:
  enabled: true
  postgresqlPassword: "password"
  volumePermissions:
    enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.26
  persistence:
    enabled: true
    storageClass: authentik-postgresql
    accessModes:
      - ReadWriteOnce

redis:
  enabled: true
  volumePermissions:
    enabled: true
  master:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.27
    persistence:
      enabled: true
      storageClass: authentik-redis
  # image:
  #   registry: docker.io
  #   repository: bitnami/redis
  #   tag: 7.0.8-debian-11-r15